cfac_2021 = Event.create!(name: "Crawfish for a Cause 2021", city: "Atlanta", state: "Georgia", location: "175 Le Brun Road", description: "The one that started it all at LeBrun")
cfac_2022 = Event.create!(name: "Crawfish for a Cause 2022", city: "Atlanta", state: "Georgia", location: "Steady Hand Brewery", description: "The first one at Steady Hand.")
mental_awakening = Event.create!(name: "Mental Awakening", city: "Atlanta", state: "Georgia", location: "Steady Hand Brewery", description: "Mental Awakening 2023")
cfac_clt = Event.create!(name: "Crawfish for a Cause Charlotte", city: "Charlotte", state: "North Carolina", location: "Suffolk Punch Brewery", description: "The one in Charlotte")

spafford = Artist.create!(name: "Spafford", logo: "spaffordLogo", spotify_url: "https://open.spotify.com/artist/7fA0IDinGo27lmOeGy6oGV?si=19d582f942284a2b", instagram_url: "https://www.instagram.com/spaffordmusic/?hl=en")
spag_west = Artist.create!(name: "Spaghetti Western", logo: "spagWestLogo", spotify_url: "https://open.spotify.com/artist/01rYhr6n1dXj2kT2g2IGZE?si=PJu9wGKTTOiqpdfW-I_HZw", instagram_url: "https://www.instagram.com/spaghettiwesternatl/?hl=en")
pluto_gang = Artist.create!(name: "Pluto Gang", logo: "plutoGangLogo", spotify_url: "https://open.spotify.com/artist/4tkYWPJLnt62UiFgek0LlU?si=3e26108b0f18469a", instagram_url: "https://www.instagram.com/plutogangband/?hl=en")
orange_constant = Artist.create!(name: "Orange Constant", logo: "orangeConstantLogo", spotify_url: "https://open.spotify.com/artist/2ZJzTxzesjXqxREe1J7YYM?si=c40c0054a4b240bd", instagram_url: "https://www.instagram.com/orangeconstant/?hl=en")
mountain_grass_unit = Artist.create!(name: "Mountain Grass Unit", logo: "mountainGrassLogo", spotify_url: "https://open.spotify.com/artist/0FWlJ725NEZpxqxjZG3yGl?si=c04e3257838b4905", instagram_url: "https://www.instagram.com/the_mountain_grass_unit/?hl=en")
airshow = Artist.create!(name: "Airshow", logo: "airshowLogo", spotify_url: "https://open.spotify.com/artist/2USLUiPGlv1amJy3gUszGw?si=s63E-FG5QmShLmsnVqCD5A", instagram_url: "https://www.instagram.com/airshowband/?hl=en")
fixins = Artist.create!(name: "The Fixin's", logo: "fixinsLogo", spotify_url: "https://open.spotify.com/artist/1vJ6XtIbCrUJmoqk2a6kV9", instagram_url: "https://www.instagram.com/thefixinsmusic/?hl=en")
frute = Artist.create!(name: "Frute", logo: "fruteLogo", spotify_url: "https://open.spotify.com/artist/58zUyObup2GjOuye4EcPRZ?si=pi61s6VlQAm0GQXRPbFaiw", instagram_url: "https://www.instagram.com/thefruteband/?hl=en")
manic_vision = Artist.create!(name: "Manic Vision", logo: "manicLogo", spotify_url: "https://open.spotify.com/artist/2CfwSh0wSIyA9323QBBw5l?si=VLrz6PxwTWyBpvYAL9okTQ", instagram_url: "https://www.instagram.com/manicvisionmusic/?hl=en")

spag_21 = ArtistEvent.create!(artist: spag_west, event: cfac_2021)
spag_22 = ArtistEvent.create!(artist: spag_west, event: cfac_2022)
spag_ma = ArtistEvent.create!(artist: spag_west, event: mental_awakening)
pg_21 = ArtistEvent.create!(artist: pluto_gang, event: cfac_2021)
oc_22 = ArtistEvent.create!(artist: orange_constant, event: cfac_2022)
oc_ma = ArtistEvent.create!(artist: orange_constant, event: mental_awakening)
mgu_ma = ArtistEvent.create!(artist: mountain_grass_unit, event: mental_awakening)
mgu_clt = ArtistEvent.create!(artist: mountain_grass_unit, event: cfac_clt)
airshow_ma = ArtistEvent.create!(artist: airshow, event: mental_awakening)
fixins_ma = ArtistEvent.create!(artist: fixins, event: mental_awakening)
frute_clt = ArtistEvent.create!(artist: frute, event: cfac_clt)
manic_22 = ArtistEvent.create!(artist: manic_vision, event: cfac_2022)

inland = Sponsor.create!(name: "Inland Seafood", description: "", logo: "random logo")
meraki = Sponsor.create!(name: "Meraki", description: "", logo: "random logo")
ivester_jackson = Sponsor.create!(name: "Ivester Jackson", description: "", logo: "random logo")
main = Sponsor.create!(name: "131 Main", description: "", logo: "random logo")
southern_cut = Sponsor.create!(name: "Southern Cut Design and Build", description: "", logo: "random logo")
vida = Sponsor.create!(name: "Vida Travel", description: "", logo: "random logo")
lfg = Sponsor.create!(name: "Live Forever Golf", description: "", logo: "random logo")
satisfied = Sponsor.create!(name: "Satisfied Entertainment", description: "", logo: "random logo")
headynet = Sponsor.create!(name: "HeadyNet", description: "", logo: "random logo")
kittle_homes = Sponsor.create!(name: "Kittle Homes", description: "", logo: "random logo")
summit = Sponsor.create!(name: "Summit Investors", description: "", logo: "random logo")
jnj = Sponsor.create!(name: "JNJ Apparel", description: "", logo: "random logo")
prime = Sponsor.create!(name: "Prime Products", description: "", logo: "random logo")
heath = Sponsor.create!(name: "Ricky Heath Plumbing", description: "", logo: "random logo")
reliable = Sponsor.create!(name: "Reliable Restoration", description: "", logo: "random logo") 
steady_hand = Sponsor.create!(name: "Steady Hand Brewery", description: "", logo: "random logo") 
eargasm = Sponsor.create!(name: "Eargasm Earplugs", description: "", logo: "random logo")  
barrys = Sponsor.create!(name: "Barry's", description: "", logo: "random logo") 
supreme_lending = Sponsor.create!(name: "Supreme Lending", description: "", logo: "random logo") 
suffolk_punch = Sponsor.create!(name: "Suffolk Punch Brewing", description: "", logo: "random logo")

blake_house = Sponsor.create!(name: "The Blake House", description: "", logo: "random logo")
will_to_live = Sponsor.create!(name: "Will to Live", description: "", logo: "random logo")
youth_villages = Sponsor.create!(name: "Youth Villages", description: "", logo: "random logo")

inland_21 = SponsorEvent.create!(sponsor: inland, event: cfac_2021)
inland_22 = SponsorEvent.create!(sponsor: inland, event: cfac_2022)
inland_ma = SponsorEvent.create!(sponsor: inland, event: mental_awakening)
meraki_clt =SponsorEvent.create!(sponsor: meraki, event: cfac_clt)
ivester_clt = SponsorEvent.create!(sponsor: ivester_jackson , event: cfac_clt)
main_clt = SponsorEvent.create!(sponsor: main, event: cfac_clt)
southern_cut_clt = SponsorEvent.create!(sponsor: southern_cut, event: cfac_clt)
vida_clt = SponsorEvent.create!(sponsor: suffolk_punch, event: cfac_clt)
barrys_clt = SponsorEvent.create!(sponsor: barrys, event: mental_awakening)
suffolk_clt = SponsorEvent.create!(sponsor: vida, event: cfac_clt)
lfg_22 = SponsorEvent.create!(sponsor: lfg, event: cfac_2022)
lfg_ma = SponsorEvent.create!(sponsor: lfg, event: mental_awakening)
satisfied_22 = SponsorEvent.create!(sponsor: satisfied, event: cfac_2022)
satisfied_ma = SponsorEvent.create!(sponsor: satisfied, event: mental_awakening)
hn_22 = SponsorEvent.create!(sponsor: headynet, event: cfac_2022)
hn_ma = SponsorEvent.create!(sponsor: headynet, event: mental_awakening)
kittle_homes_22 = SponsorEvent.create!(sponsor: kittle_homes, event: cfac_2022)
kittle_homes_ma = SponsorEvent.create!(sponsor: kittle_homes, event: mental_awakening)
summit_22 = SponsorEvent.create!(sponsor: summit, event: cfac_2022)
summit_ma = SponsorEvent.create!(sponsor: summit, event: mental_awakening)
jnj_22 = SponsorEvent.create!(sponsor: jnj, event: cfac_2022)
jnj_ma = SponsorEvent.create!(sponsor: jnj, event: mental_awakening)
prime_22 = SponsorEvent.create!(sponsor: prime, event: cfac_2022)
prime_ma = SponsorEvent.create!(sponsor: prime, event: mental_awakening)
reliable_22 = SponsorEvent.create!(sponsor: reliable, event: cfac_2022)
reliable_ma = SponsorEvent.create!(sponsor: reliable, event: mental_awakening)
steady_hand_22 = SponsorEvent.create!(sponsor: steady_hand, event: cfac_2022)
steady_hand_ma = SponsorEvent.create!(sponsor: steady_hand, event: mental_awakening)
heath_ma = SponsorEvent.create!(sponsor: heath, event: mental_awakening)
eargasm_ma = SponsorEvent.create!(sponsor: eargasm, event: mental_awakening)
supreme_lending_ma = SponsorEvent.create!(sponsor: supreme_lending, event: mental_awakening)

blake_21 = SponsorEvent.create!(sponsor: blake_house, event: cfac_2021)
blake_22 = SponsorEvent.create!(sponsor: blake_house, event: cfac_2022)
blake_ma = SponsorEvent.create!(sponsor: blake_house, event: mental_awakening)
will_22 = SponsorEvent.create!(sponsor: will_to_live, event: cfac_2022)
will_ma = SponsorEvent.create!(sponsor: will_to_live, event: mental_awakening)
yv_clt = SponsorEvent.create!(sponsor: youth_villages, event: cfac_clt)

yumbii = Vendor.create!(name: "Yumbii", description: "Yumbii")
pats = Vendor.create!(name: "Pat's Poutine", description: "Pat's Poutine")
hd_prep = Vendor.create!(name: "HD PREP", description: "HD PREP")
papa_padgett = Vendor.create!(name: "Papa Padgett", description: "Papa Padgett")
phews_pies = Vendor.create!(name: "Phew's Pies", description: "Phew's Pies")

yumbii_ma = VendorEvent.create!(vendor: yumbii, event: mental_awakening)
pats_ma = VendorEvent.create!(vendor: pats, event: mental_awakening)
hd_prep_ma = VendorEvent.create!(vendor: hd_prep, event: mental_awakening)
papa_padgett_ma = VendorEvent.create!(vendor: papa_padgett, event: mental_awakening)
phews_pies_ma = VendorEvent.create!(vendor: phews_pies, event: mental_awakening)




